<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_txtPassword</name>
   <tag></tag>
   <elementGuidId>ec6b882e-9e2d-4238-97cb-d08619348e32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3c20e16-ae36-42a5-a4ce-ce80e7da2263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtPassword</value>
      <webElementGuid>4f342e59-9a81-4142-8846-762fceb8556d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPassword</value>
      <webElementGuid>161d7352-366d-4670-a676-ad2efb8f098d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>077d1b4b-7f28-4c7a-b875-d553dabf377a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>09d67799-4382-459b-83a3-0ea84cdd84bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPassword&quot;)</value>
      <webElementGuid>bae9171f-4856-4942-a740-488f2f74688e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPassword']</value>
      <webElementGuid>a838dc27-16a5-4055-ad2c-50a5f1fb51e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divPassword']/input</value>
      <webElementGuid>063f594f-a403-4cee-b3a6-c4b33bed6287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>59a25898-d560-4838-8624-8a66fc72c227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtPassword' and @id = 'txtPassword' and @type = 'password']</value>
      <webElementGuid>656dd2ba-3a5a-48d3-b4ea-c3a63790fc4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
