<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_searchSystemUseruserName</name>
   <tag></tag>
   <elementGuidId>92927d3e-126f-4832-9889-148d37602ec2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchSystemUser_userName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchSystemUser_userName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75d6d574-78a5-41c5-923c-bbacc21cc926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d7d4320-5387-4c76-bf68-6e48b6a3939e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchSystemUser[userName]</value>
      <webElementGuid>1d14ff52-42a6-463f-b04f-77bf13f49620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchSystemUser_userName</value>
      <webElementGuid>c6201d29-b5c4-4c9b-8e49-d7a724f5e9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchSystemUser_userName&quot;)</value>
      <webElementGuid>4685b84f-4a1e-4b09-8970-b2289a71ec89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchSystemUser_userName']</value>
      <webElementGuid>2debb9bb-0e9d-4c78-8a5c-dd478b188380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/fieldset/ol/li/input</value>
      <webElementGuid>e3921a43-7bf0-4563-9b2b-9f18e74fab0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>1d7980ef-64b9-4477-84d1-6b3d91299df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'searchSystemUser[userName]' and @id = 'searchSystemUser_userName']</value>
      <webElementGuid>a655b8a0-eac7-4d6c-b098-e76569f2922e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
