<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_chkSelectAll</name>
   <tag></tag>
   <elementGuidId>4dc12e3a-d0e8-4d7a-bf55-4a349b4d6473</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ohrmList_chkSelectAll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ohrmList_chkSelectAll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8dd26c97-b3b5-45cd-9325-4868940f46cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a26d1362-1b2a-4f0f-950f-0d5b45e95423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ohrmList_chkSelectAll</value>
      <webElementGuid>ec811140-aa95-47ff-ba30-4f8eba52a8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chkSelectAll</value>
      <webElementGuid>52805df6-0edb-4997-a423-00b752057dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ohrmList_chkSelectAll&quot;)</value>
      <webElementGuid>cb277ead-9a5e-4a0a-8eab-34fad996c4b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ohrmList_chkSelectAll']</value>
      <webElementGuid>0ca8e102-42ed-42d1-acc4-f47da65bd923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='resultTable']/thead/tr/th/input</value>
      <webElementGuid>87d0a301-f0f4-4b6b-b9c9-f5eb2ce5e17a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/input</value>
      <webElementGuid>871d82ff-c1c3-4e13-86ec-192e8c954c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ohrmList_chkSelectAll' and @name = 'chkSelectAll']</value>
      <webElementGuid>d31c4b67-44dc-46a4-828a-c21b5e33bfc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
