<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__systemUseruserName</name>
   <tag></tag>
   <elementGuidId>3989311f-6ae0-4c42-b079-749141c41c8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#systemUser_userName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='systemUser_userName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28b26170-5e09-4e76-87f5-6c48d967fab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText</value>
      <webElementGuid>17d12559-7569-4500-a7ad-cd6a6cea75c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>7d5f8d00-af19-4196-a31c-063f0c94bed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>838868fa-3d10-46ba-83ad-d90a193c4931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>systemUser[userName]</value>
      <webElementGuid>cf7d1fe1-ec97-4ee2-9e42-fa0d6eebdc23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>systemUser_userName</value>
      <webElementGuid>c19a8792-48af-4ac5-9230-c1f484d6d4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;systemUser_userName&quot;)</value>
      <webElementGuid>6f7f63c6-cd79-4bd5-b676-326a2ed76ee2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='systemUser_userName']</value>
      <webElementGuid>4bb74836-8605-4e0b-8c2b-784dcf700634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSystemUser']/fieldset/ol/li[3]/input</value>
      <webElementGuid>c0f3b5cb-6b80-4b2e-9c93-298b69c9103d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/input</value>
      <webElementGuid>3fcdcadb-52eb-409f-8546-1cef4e12fcbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'systemUser[userName]' and @id = 'systemUser_userName']</value>
      <webElementGuid>3dd616e9-9f39-44ab-8b08-883214f30056</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
