<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__systemUseremployeeNameempName</name>
   <tag></tag>
   <elementGuidId>e1fed2db-b875-4859-91b2-20bdf98bc25b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#systemUser_employeeName_empName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='systemUser_employeeName_empName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2eae7663-d561-4eea-8c71-95de71fe6a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText ac_input</value>
      <webElementGuid>08714fa7-48ea-495f-a5ca-f411b23efe0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>51a23ca2-e3ee-4b76-9464-62bd2a49e34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Type for hints...</value>
      <webElementGuid>41c6e8b2-fb68-4ca8-b31e-1a330871df7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>06b36b2b-1b30-4fe5-9727-0f096171236a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>systemUser[employeeName][empName]</value>
      <webElementGuid>fe51ad02-7692-4b25-be2a-d3de6b327e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>systemUser_employeeName_empName</value>
      <webElementGuid>bada8085-d126-4e7c-9935-24eddd4bfd4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>70a6cb21-7612-47cc-be6f-dd0756e0fee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;systemUser_employeeName_empName&quot;)</value>
      <webElementGuid>23320b8d-b392-4060-b8eb-2c4bc35590dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='systemUser_employeeName_empName']</value>
      <webElementGuid>c20a9b53-0263-466d-9012-067902ac8ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSystemUser']/fieldset/ol/li[2]/input</value>
      <webElementGuid>3b0cf6d2-8ec9-461b-beca-456a3f66d3b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>22e84822-68dd-4394-b563-8cb68377aa58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'systemUser[employeeName][empName]' and @id = 'systemUser_employeeName_empName']</value>
      <webElementGuid>79572367-4427-4598-b8bd-ae8e7e57d647</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
