<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_searchSystemUseruserName</name>
   <tag></tag>
   <elementGuidId>1993f338-a101-438b-830f-2d028def23e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchSystemUser_userName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchSystemUser_userName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe366e62-68c6-4746-9951-d52f8725f9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92bc50f6-eebb-443c-b5b6-af813a4c94e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchSystemUser[userName]</value>
      <webElementGuid>16498507-476b-410c-afb2-527f30d3c378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchSystemUser_userName</value>
      <webElementGuid>ba7e9ff7-1c10-49cc-b0f9-3183b19dd699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchSystemUser_userName&quot;)</value>
      <webElementGuid>08417244-48b9-4bd0-ab51-95bdde3354aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchSystemUser_userName']</value>
      <webElementGuid>66044d32-4b9b-4e27-8060-7ec0d8969c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/fieldset/ol/li/input</value>
      <webElementGuid>25fcc68a-3276-4e20-be03-a7c470bd7400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>6fe1937c-e323-40ee-83d6-31120cc1b54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'searchSystemUser[userName]' and @id = 'searchSystemUser_userName']</value>
      <webElementGuid>c36881b4-d646-4c98-8fc3-407010fe25aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
