<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btnSave</name>
   <tag></tag>
   <elementGuidId>57b070ab-68d6-4179-93dc-5ecb4b88503e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnSave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fb678f8-74b2-4078-9813-9f931618ac9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>54f048e3-f964-483a-8c79-8874c224bcdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addbutton hover</value>
      <webElementGuid>c067ab6c-1604-48c7-9728-00b71904c121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnSave</value>
      <webElementGuid>c5147b5e-82c3-4d22-8c85-af29855edbf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSave</value>
      <webElementGuid>d8fe9b71-70db-4736-bf15-5635c4681d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>7f5ef520-4d2d-4060-a79e-c20c00381283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSave&quot;)</value>
      <webElementGuid>f75ba604-072e-4bdb-88b3-0abf83a7bebf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnSave']</value>
      <webElementGuid>742a8a13-7fcf-4f9a-abc1-274de369c284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSystemUser']/fieldset/p/input</value>
      <webElementGuid>00f290e8-7b8c-4ccb-b36c-f53e8faa212e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>d128b5b2-6922-49ee-8d57-409573079886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btnSave' and @id = 'btnSave']</value>
      <webElementGuid>449509dd-1fe4-431a-a292-6e52cd55f987</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
